version: '3.8'

services:
  calendar-test:
    image: postgres:latest
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - 5432:5432
    volumes:
      - calendar-test-data:/var/lib/postgresql/data:cached
    restart: always

volumes:
  calendar-test-data:
